apiVersion: apps/v1
kind: Deployment
metadata:
  name: freeswitch
  namespace: voip-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: freeswitch
  template:
    metadata:
      labels:
        app: freeswitch
    spec:
      containers:
      - name: freeswitch
        image: vishalk17/freeswitch-1.10.9:v1.1
        ports:
        - containerPort: 5060
        - containerPort: 5061
        - containerPort: 5066
        - containerPort: 5080
        - containerPort: 7443
        - containerPort: 8021
