version: '2'
services:
   freeswitch:
     build:
       context: .
       dockerfile: Dockerfile
     hostname: freeswitch
     container_name: freeswitch
     network_mode: "host"
     restart: always
     image: fs
