version: '3.8'

services:
  postgresql:
    image: postgres:13
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: freeswitch
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fs_net
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  freeswitch:
    build: .
    container_name: freeswitch
    image: vishalk17/freeswitch-1.10.12:v1.0 
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - fs_net
    ports:
      - "5060:5060/tcp"
      - "5060:5060/udp"
      - "5061:5061/tcp"
      - "5080:5080/tcp"
      - "5080:5080/udp"
      - "8021:8021/tcp"
    restart: always
    cap_add:
      - SYS_NICE
      - SYS_RESOURCE

volumes:
  postgres_data:

networks:
  fs_net:
    driver: bridge
