apiVersion: v1
kind: Service
metadata:
  name: freeswitch-svc
  namespace: voip-system
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb" # Use AWS NLB
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing" # Expose the NLB to the internet
spec:
  selector:
    app: freeswitch
  ports:
  - name: sip-udp
    port: 5060
    protocol: UDP
    targetPort: 5060
  - name: sip-tcp
    port: 5060
    protocol: TCP
    targetPort: 5060
  - name: sip-tls
    port: 5061
    protocol: TCP
    targetPort: 5061
  - name: sip-alt
    port: 5066
    protocol: TCP
    targetPort: 5066
  - name: ws-udp
    port: 5080
    protocol: UDP
    targetPort: 5080
  - name: ws-tcp
    port: 5080
    protocol: TCP
    targetPort: 5080
  - name: https-alt
    port: 7443
    protocol: TCP
    targetPort: 7443
  - name: event-socket
    port: 8021
    protocol: TCP
    targetPort: 8021
  type: LoadBalancer
